[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
solana_staking = "Ft9XAg4Uhqg36yydXY54UurH6KQPyqtLhQnTPYPoLun7"
solana_staking_blog = "Ft9XAg4Uhqg36yydXY54UurH6KQPyqtLhQnTPYPoLun7"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
